[info]
title = "Informações do Projeto"
version = "1.0"
author = "John Doe"
created_at = 2023-05-01

[config]
server = "example.com"
port = 8080
timeout = 30

[users]
[users.admin]
username = "admin"
password = "admin123"
roles = ["admin", "manager"]

[users.viewer]
username = "viewer1"
password = "pass123"
roles = ["viewer"]

[features]
feature1 = true
feature2 = false
feature3 = true
