# Exemplo de arquivo TOML

title = "Configurações do Sistema"
author = "John Doe"

[database]
server = "localhost"
port = 5432
username = "admin"
password = "secretpassword"

[server]
ip = "192.168.0.1"
port = 8080
ssl_enabled = true

[logs]
enabled = true
path = "/var/log/application.log"
level = "info"
