
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BASIC_STRING BOOLEAN COMMA COMMENT DATE DATE_TIME EQUALS IP KEY LBRACKET LITERAL_STRING NUMBER OBJECT RBRACKET STRING SUBOBJECT TIMEFT : Section_listSection_list : Section Section_listSection_list : SectionSection  : LBRACKET Section_name RBRACKET Section_contentSection  : LBRACKET Section_name RBRACKET SubsectionSection  : ContentSection  : TableTable : LBRACKET LBRACKET Section_name RBRACKET RBRACKET Section_content TableTable : LBRACKET LBRACKET Section_name RBRACKET RBRACKET Section_contentSubsection : LBRACKET Subsection_name RBRACKET Section_content SubsectionSubsection : LBRACKET Subsection_name RBRACKET Section_contentSection_name : OBJECTSubsection_name : SUBOBJECTSection_content : Content Section_contentSection_content : ContentSection_content : COMMENTContent : Key EQUALS ValueKey : KEYValue : BASIC_STRING\n             | LITERAL_STRING\n             | STRING\n             | NUMBER\n             | IP\n             | DATE\n             | TIME\n             | BOOLEAN\n             | Array\n             | DATE_TIME\n            Array : LBRACKET Value_list RBRACKET Value_list : Value COMMA Value_list\n                  | Value'
    
_lr_action_items = {'LBRACKET':([0,3,4,5,6,13,15,16,17,18,19,20,21,22,23,24,25,26,27,30,31,32,33,39,40,41,42,45,46,47,48,],[4,4,10,-6,-7,27,29,-17,-19,-20,-21,-22,-23,-24,-25,-26,-27,-28,27,-4,-5,-15,-16,-14,-29,27,45,10,-8,29,-10,]),'KEY':([0,3,5,6,15,16,17,18,19,20,21,22,23,24,25,26,30,31,32,33,36,39,40,42,43,46,47,48,],[8,8,-6,-7,8,-17,-19,-20,-21,-22,-23,-24,-25,-26,-27,-28,-4,-5,8,-16,8,-14,-29,-9,8,-8,-11,-10,]),'$end':([1,2,3,5,6,9,16,17,18,19,20,21,22,23,24,25,26,30,31,32,33,39,40,42,46,47,48,],[0,-1,-3,-6,-7,-2,-17,-19,-20,-21,-22,-23,-24,-25,-26,-27,-28,-4,-5,-15,-16,-14,-29,-9,-8,-11,-10,]),'OBJECT':([4,10,],[12,12,]),'EQUALS':([7,8,],[13,-18,]),'RBRACKET':([11,12,14,17,18,19,20,21,22,23,24,25,26,28,34,35,37,38,40,44,],[15,-12,28,-19,-20,-21,-22,-23,-24,-25,-26,-27,-28,36,40,-31,43,-13,-29,-30,]),'BASIC_STRING':([13,27,41,],[17,17,17,]),'LITERAL_STRING':([13,27,41,],[18,18,18,]),'STRING':([13,27,41,],[19,19,19,]),'NUMBER':([13,27,41,],[20,20,20,]),'IP':([13,27,41,],[21,21,21,]),'DATE':([13,27,41,],[22,22,22,]),'TIME':([13,27,41,],[23,23,23,]),'BOOLEAN':([13,27,41,],[24,24,24,]),'DATE_TIME':([13,27,41,],[26,26,26,]),'COMMENT':([15,16,17,18,19,20,21,22,23,24,25,26,32,36,40,43,],[33,-17,-19,-20,-21,-22,-23,-24,-25,-26,-27,-28,33,33,-29,33,]),'COMMA':([17,18,19,20,21,22,23,24,25,26,35,40,],[-19,-20,-21,-22,-23,-24,-25,-26,-27,-28,41,-29,]),'SUBOBJECT':([29,],[38,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'FT':([0,],[1,]),'Section_list':([0,3,],[2,9,]),'Section':([0,3,],[3,3,]),'Content':([0,3,15,32,36,43,],[5,5,32,32,32,32,]),'Table':([0,3,42,],[6,6,46,]),'Key':([0,3,15,32,36,43,],[7,7,7,7,7,7,]),'Section_name':([4,10,],[11,14,]),'Value':([13,27,41,],[16,35,35,]),'Array':([13,27,41,],[25,25,25,]),'Section_content':([15,32,36,43,],[30,39,42,47,]),'Subsection':([15,47,],[31,48,]),'Value_list':([27,41,],[34,44,]),'Subsection_name':([29,],[37,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> FT","S'",1,None,None,None),
  ('FT -> Section_list','FT',1,'p_FT','yacc.py',43),
  ('Section_list -> Section Section_list','Section_list',2,'p_Section_list1','yacc.py',47),
  ('Section_list -> Section','Section_list',1,'p_Section_list2','yacc.py',51),
  ('Section -> LBRACKET Section_name RBRACKET Section_content','Section',4,'p_Section1','yacc.py',55),
  ('Section -> LBRACKET Section_name RBRACKET Subsection','Section',4,'p_Section2','yacc.py',59),
  ('Section -> Content','Section',1,'p_Section3','yacc.py',63),
  ('Section -> Table','Section',1,'p_Section4','yacc.py',67),
  ('Table -> LBRACKET LBRACKET Section_name RBRACKET RBRACKET Section_content Table','Table',7,'p_Table1','yacc.py',71),
  ('Table -> LBRACKET LBRACKET Section_name RBRACKET RBRACKET Section_content','Table',6,'p_Table2','yacc.py',80),
  ('Subsection -> LBRACKET Subsection_name RBRACKET Section_content Subsection','Subsection',5,'p_Subsection1','yacc.py',84),
  ('Subsection -> LBRACKET Subsection_name RBRACKET Section_content','Subsection',4,'p_Subsection2','yacc.py',89),
  ('Section_name -> OBJECT','Section_name',1,'p_Section_name','yacc.py',93),
  ('Subsection_name -> SUBOBJECT','Subsection_name',1,'p_Subsection_name','yacc.py',97),
  ('Section_content -> Content Section_content','Section_content',2,'p_Section_content1','yacc.py',101),
  ('Section_content -> Content','Section_content',1,'p_Section_content2','yacc.py',105),
  ('Section_content -> COMMENT','Section_content',1,'p_Section_content3','yacc.py',109),
  ('Content -> Key EQUALS Value','Content',3,'p_Content','yacc.py',113),
  ('Key -> KEY','Key',1,'p_Key','yacc.py',117),
  ('Value -> BASIC_STRING','Value',1,'p_Value','yacc.py',121),
  ('Value -> LITERAL_STRING','Value',1,'p_Value','yacc.py',122),
  ('Value -> STRING','Value',1,'p_Value','yacc.py',123),
  ('Value -> NUMBER','Value',1,'p_Value','yacc.py',124),
  ('Value -> IP','Value',1,'p_Value','yacc.py',125),
  ('Value -> DATE','Value',1,'p_Value','yacc.py',126),
  ('Value -> TIME','Value',1,'p_Value','yacc.py',127),
  ('Value -> BOOLEAN','Value',1,'p_Value','yacc.py',128),
  ('Value -> Array','Value',1,'p_Value','yacc.py',129),
  ('Value -> DATE_TIME','Value',1,'p_Value','yacc.py',130),
  ('Array -> LBRACKET Value_list RBRACKET','Array',3,'p_Array','yacc.py',135),
  ('Value_list -> Value COMMA Value_list','Value_list',3,'p_Value_list','yacc.py',139),
  ('Value_list -> Value','Value_list',1,'p_Value_list','yacc.py',140),
]
